### ISSUE TITLE
Catkinize pr2_robot

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#224]
Catkinize pr2_robot for Hydro. Depends on catkinizing and releasing:
- [x] prosilica_driver (formerly camera_drivers)
- [x] wge100_driver (formerly camera_drivers)
- [x] tf2_ros (release only; formerly geometry_experimental)
- [x] microstrain_3dgmx2_imu (formerly imu_drivers)
- [x] ps3joy (release only, formerly joystick_drivers)
- [x] hokuyo_node (formerly laser_drivers)
- [x] robot_pose_ekf (formerly navigation)
- [x] python_orocos_kdl (formerly orocos_kinematics_dynamics)
- [x] PR2/pr2_common#214
- [x] PR2/pr2_controllers#365
- [x] PR2/pr2_ethercat_drivers#58
- [x] PR2/pr2_mechanism#313
- [x] PR2/pr2_power_drivers#61
- [x] robot_state_publisher (catkinized and released but not building)
- [x] wifi_ddwrt (formerly wifi_drivers)

**Comment by jonbinney** [comment]
geometry_experimental refers to TF2, right? That appears to be catkinized. Also navigation is catkinized in hydro.

**Comment by ahendrix** [comment]
I'm not sure which packages the geometry_experimental stack dependency is referring to.

Also note that this is pending on both catkinization and RELEASE of all of the packages that are listed. Neither tf2 nor navigation are released into Hydro yet.

**Comment by ahendrix** [comment]
Confirmed; the geometry_experimental dependency is a dependency on tf2_ros, since the tf2_ros buffer server is part of the PR2 bringup.

**Comment by ahendrix** [comment]
DONE! Booyah!

**Comment by jonbinney** [comment]
hooray!
